name: Run Backend Tests

on:
  push: 
    branches: ["dev-backend"]
    paths:
      - 'backend/**'
      
  pull_request:
    branches: ["dev-backend"]
    paths:
      - 'backend/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python 3.10.18
        uses: actions/setup-python@v5
        with:
          python-version: "3.10.18"
        
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          pip install -r backend/requirements.txt
        
      - name: Run tests with pytest
        env:
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_NAME: ${{ secrets.DB_NAME }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
        run: |
          PYTHONPATH=$PWD pytest backend/tests/ --maxfail=1 --disable-warnings -q