name: Run Backend Tests

on:
  push: 
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python 3.10.18
        uses: actions/setup-python@v5
        with:
          python-version: "3.10.18"
        
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          pip install -r backend/requirements.txt
        
      - name: Run tests with pytest
        run: |
          pytest backend/tests/test_main.py